target 'RNWithPeerTalk' do
  platform :ios, '9.0'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # PeerTalk
  pod 'PeerTalk', :git => 'https://github.com/rsms/peertalk.git', :branch => 'master'
  pod 'CocoaAsyncSocket'
end

target 'RNWithPeerTalk-Mac' do
  platform :osx, '10.12'
  pod 'PeerTalk', :git => 'https://github.com/rsms/peertalk.git', :branch => 'master'
  pod 'CocoaAsyncSocket'
end
